name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  # renovate: datasource=github-releases depName=tailscale/tailscale
  TAILSCALE_VERSION: v1.84.0

concurrency:
  group: ${{ github.ref_name || 'ci' }}
  cancel-in-progress: true
jobs:
  tailscale-idp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tailscale/tailscale
          ref: ${{ env.TAILSCALE_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker arc meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/daviddriscoll/tailscale-idp
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Arc
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ./cmd/tsidp/Dockerfile
          context: ./
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Imageid
        run: echo ${{ steps.build.outputs.imageid }}
